// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvLBsM5RREXXYjeL7MUjqE5y8y5imUMJA',
    appId: '1:229916388388:web:9c60e5524d2beba127fcb1',
    messagingSenderId: '229916388388',
    projectId: 'contact-c61f6',
    authDomain: 'contact-c61f6.firebaseapp.com',
    storageBucket: 'contact-c61f6.appspot.com',
    measurementId: 'G-WD4LWZJ305',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE5ayvswOICMX8WDeGAGXe1t-0_f-YvU8',
    appId: '1:229916388388:android:5c763ac6981bb34127fcb1',
    messagingSenderId: '229916388388',
    projectId: 'contact-c61f6',
    storageBucket: 'contact-c61f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSnV9y7liSeEOv10p-DJRJcWAHyog1Rgg',
    appId: '1:229916388388:ios:fe576a2f96146f0227fcb1',
    messagingSenderId: '229916388388',
    projectId: 'contact-c61f6',
    storageBucket: 'contact-c61f6.appspot.com',
    iosBundleId: 'com.example.myContact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSnV9y7liSeEOv10p-DJRJcWAHyog1Rgg',
    appId: '1:229916388388:ios:fe576a2f96146f0227fcb1',
    messagingSenderId: '229916388388',
    projectId: 'contact-c61f6',
    storageBucket: 'contact-c61f6.appspot.com',
    iosBundleId: 'com.example.myContact',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvLBsM5RREXXYjeL7MUjqE5y8y5imUMJA',
    appId: '1:229916388388:web:480f81fb6c8f5e8227fcb1',
    messagingSenderId: '229916388388',
    projectId: 'contact-c61f6',
    authDomain: 'contact-c61f6.firebaseapp.com',
    storageBucket: 'contact-c61f6.appspot.com',
    measurementId: 'G-F50M9KT9DL',
  );
}
